# https://hydra.cc/docs/configure_hydra/intro/
# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog
# output directory, generated dynamically on each run
run:
  dir: ${paths.experiment_dir}
output_subdir: ${hydra.run.dir}.hydra/  # store .hydra configs in here
sweep:
  dir: ${hydra.run.dir}multiruns/ #${now:%Y-%m-%d}_${now:%H-%M-%S}/
  subdir: ${hydra.job.num}/
