# csv logger built in lightning   """Creates logs in save_dir/name/version."""
csv:
  _target_: pytorch_lightning.loggers.csv_logs.CSVLogger
  save_dir: ${paths.experiment_dir}
  name:  ${paths.metrics_dir}
  prefix: ""
