name: shape_augs_gpu
train:
  - _target_: kornia.augmentation.RandomHorizontalFlip
    p: 0.5
  - _target_: kornia.augmentation.RandomVerticalFlip
    p: 0.5
#  - _target_: kornia.augmentation.RandomRotation
#    degrees: 90.0
#    p: 0.5
  - _target_: drop.transforms.transformations.Normalize
    mean: ${norms.mean}
    std: ${norms.std}
  - _target_: drop.transforms.transformations.ZeroPadTensor
    size: ${tiling.outsize}
no_train:
  - _target_: drop.transforms.transformations.Normalize
    mean: ${norms.mean}
    std: ${norms.std}
  - _target_: drop.transforms.transformations.ZeroPadTensor
    size: ${tiling.outsize}