_target_: drop.lit_modules.cls.mil_module.RegionMILModule
loss_fn:
  _target_: torch.nn.CrossEntropyLoss
weight_decay: 0.0005
lr: 0.0005
optimizer: "Adam"
scheduler: ${lr_scheduler}
monitor: "val/loss"
