name: "CosineAnnealingLR"
scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: 3  # make similar to stepsize
  eta_min: 0
  last_epoch: -1
  verbose: true